# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# black code formatter github action: https://github.com/marketplace/actions/black-code-formatter

name: Linting

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      shell: bash -l {0}
      run: |
        flake8 --config .flake8
